### ISSUE TITLE
please use HDF reader for matlab v7.3 files

### ISSUE THREAD

**Issue by Dave-SUN** [boazarad/NTIRE2020_spectral#4]
When I evaluate the experiment results, it always shows "please use HDF reader for matlab v7.3 files", how can I evaluate the mat files? Thank you!

**Comment by liuyulvv** [comment]
Hello, can you provide the link to download the dataset, I applied to participate in the competition on codalab, no news yet, thank you

**Comment by boazarad** [comment]
@Dave-SUN you are saving results as Mat v7.3 instead of v7.2, please see example code.

@liuyulvv  Please see https://github.com/boazarad/NTIRE2022_spectral
